<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.oxipro.cmu.configlang</groupId>
        <artifactId>cmu-config-lang</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>velocity</artifactId>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.velocitypowered</groupId>
            <artifactId>velocity-api</artifactId>
            <version>3.5.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
<!--        &lt;!&ndash; add the annotation processor &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>com.velocitypowered</groupId>-->
<!--            <artifactId>velocity-api</artifactId>-->
<!--            <version>3.5.0-SNAPSHOT</version>-->
<!--            <type>processor</type>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.oxipro.cmu.configlang</groupId>
            <artifactId>api</artifactId>
            <version>1.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.oxipro.cssdb</groupId>
            <artifactId>cssdb-api</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.oxipro.cmu.configlang</groupId>
            <artifactId>common</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>

</project>